FROM ubuntu:25.10

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt upgrade -y

# Install Debian build deps
RUN apt install -y \
    build-essential \
    devscripts \
    debhelper \
    decopy \
    dh-cargo \
    equivs \
    sbuild \
    schroot \
    debootstrap \
    eatmydata \
    fakeroot \
    git \
    ca-certificates

RUN useradd -m builder && usermod -aG sbuild builder

USER builder
WORKDIR /home/builder
