FROM ubuntu:26.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt upgrade -y

# Install Debian build deps
RUN apt install -y \
    build-essential \
    devscripts \
    debhelper \
    decopy \
    dh-cargo \
    equivs \
    sbuild \
    schroot \
    debootstrap \
    eatmydata \
    fakeroot \
    git \
    curl \
    ca-certificates

RUN useradd -m builder && usermod -aG sbuild builder

USER builder
ENV RUSTUP_HOME=/home/builder/.rustup \
    CARGO_HOME=/home/builder/.cargo \
    PATH=/home/builder/.cargo/bin:$PATH
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
RUN rustup default stable
WORKDIR /home/builder
