SHELL			:= /bin/bash
PACKAGE			:= ags-unstable
VERSION			:= 2.3.0
COMMIT_HASH     := bbee2f1
BUILD           :=
REVISION		:= 1
REPOSITORY		:= https://github.com/Aylur/ags.git
TARGET			?= resolute
URGENCY 		?= medium
PPA				?= ppa:razvanalex/hyprland-ppa
ROOT			:= $(shell pwd)/../../
PACKAGE_ROOT    := $(ROOT)/ppa/$(PACKAGE)/
BUILD_ROOT		:= $(PACKAGE_ROOT)/build/

include $(ROOT)/Makefile.defs

prepare:
