SHELL			:= /bin/bash
PACKAGE			:= ags-unstable
VERSION			:= 2.3.0
COMMIT_HASH		:= 772f6ad
BUILD           :=
REVISION		:= 1
REPOSITORY		:= https://github.com/Aylur/ags.git
TARGET  		?= plucky
URGENCY 		?= medium
DEBFULLNAME 	?=
DEBEMAIL    	?=
PPA				?= ppa:razvanalex/hyprland-ppa
ROOT			:= $(shell pwd)/../../
PACKAGE_ROOT    := $(ROOT)/ppa/$(PACKAGE)/
BUILD_ROOT		:= $(PACKAGE_ROOT)/build/

include $(ROOT)/Makefile.defs

prepare:
