SHELL			:= /bin/bash
PACKAGE			:= astal
REPOSITORY		:= https://github.com/Aylur/astal.git
VERSION			:= 0.1.0
COMMIT_HASH		:= 71b008e
BUILD           :=
REVISION		:= 1
STATUS			:=
TARBALL_URL		:=
TARGET  		?= plucky
URGENCY 		?= medium
DEBFULLNAME 	?=
DEBEMAIL    	?=
PPA				?= ppa:razvanalex/hyprland-ppa
ROOT			:= $(shell pwd)/../../
PACKAGE_ROOT    := $(ROOT)/ppa/astal/
BUILD_ROOT		:= $(PACKAGE_ROOT)/build/

include $(ROOT)/Makefile.defs

prepare:
