SHELL			:= /bin/bash
PACKAGE			:= appmenu-glib-translator
REPOSITORY		:= https://github.com/rilian-la-te/vala-panel-appmenu.git
VERSION			:= 25.04
COMMIT_HASH		:= 6665f77
BUILD           :=
REVISION		:= 1
STATUS			:=
TARBALL_URL		:=
TARGET  		?= questing
URGENCY 		?= medium
DEBFULLNAME 	?=
DEBEMAIL    	?=
PPA				?= ppa:razvanalex/hyprland-ppa
ROOT			:= $(shell pwd)/../../
PACKAGE_ROOT    := $(ROOT)/ppa/$(PACKAGE)/
BUILD_ROOT		:= $(PACKAGE_ROOT)/build/

include $(ROOT)/Makefile.defs

prepare:
